#!/bin/sh

PROJ_ROOT="$(cd "$(dirname "$0")" && pwd)/"

# stopping nginx
PID="$PROJ_ROOT/logs/nginx.pid"
if [ -f "$PID" ]; then
	kill -INT $(cat "$PID")
else
	echo "nginx wasn't started (no pid file found)"
fi
